package edu.cs6510.monolith_server.transaction;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

import java.math.BigDecimal;

@Entity
@Table(
        // Creates the persistent transaction_items table. Each row represents a unique SKU in a transaction, with a quantity that increments if the same SKU is scanned multiple times.
        name = "transaction_items",
        // The unique constraint ensures that each SKU is only stored once per transaction. If a customer scans the same SKU twice, the quantity becomes 2 instead of creating duplicate rows.
        // This constraint prevents duplicate rows for the same SKU in a single transaction, ensuring data integrity and accurate item counts.
        // The unique constraint is defined on the combination of transaction_id and sku columns, ensuring that each SKU is only stored once per transaction.
        // The unique constraint is named "unique_transaction_sku" for clarity and ease of reference in the database schema.
        // The unique constraint is defined using the @UniqueConstraint annotation, which specifies the name of the constraint and the columns that make up the unique key.
        uniqueConstraints = @UniqueConstraint(
                name = "unique_transaction_sku",
                columnNames = {"transaction_id", "sku"}
        )
)
//This stores one row per SKU in a transaction. If a customer scans the same SKU twice, the quantity becomes 2 instead of creating duplicate rows.
public class TransactionItem {

    // The @Id annotation is used to specify that the id field is the primary key of the TransactionItem entity.
    // The @GeneratedValue annotation is used to specify that the id field should be automatically generated by the database when a new TransactionItem entity is persisted. 
    // The strategy = GenerationType.IDENTITY indicates that the database should use an auto-incrementing identity column to generate unique values for the id field. 
    // This ensures that each TransactionItem has a unique identifier, which is important for maintaining data integrity and enabling efficient retrieval of specific items in a transaction.
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // The @ManyToOne annotation is used to specify that the transaction field is a many-to-one relationship with the CheckoutTransaction entity.
    // The fetch = FetchType.LAZY indicates that the CheckoutTransaction entity should be loaded lazily, meaning that it will only be loaded from the database when it is accessed for the first time.
    // The optional = false indicates that the transaction field is required and cannot be null. This ensures that each TransactionItem is associated with a valid CheckoutTransaction, which is important for maintaining data integrity and enabling efficient retrieval of items in a transaction.
    // The @JoinColumn annotation is used to specify the name of the foreign key column in the transaction_items table that references the primary key of the checkout_transactions table.
    // The name = "transaction_id" specifies that the foreign key column should be named transaction_id, which is consistent with the naming convention used in the CheckoutTransaction entity.
    // The nullable = false indicates that the foreign key column cannot be null, which ensures that each TransactionItem is associated with a valid CheckoutTransaction.
    // Overall, these annotations are used to define the relationship between the TransactionItem and CheckoutTransaction entities, and to ensure that each TransactionItem is associated with a valid CheckoutTransaction in the database.
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "transaction_id", nullable = false)
    private CheckoutTransaction transaction;
    
    // The @Column annotation is used to specify the properties of the sku field in the transaction_items table.
    // The nullable = false indicates that the sku field cannot be null, which ensures that each TransactionItem has a valid SKU.
    // The length = 32 specifies that the maximum length of the sku field is 32 characters, which is consistent with the length of the SKU field in the Product entity.
    @Column(nullable = false, length = 32)
    private String sku;

    // The @Column annotation is used to specify the properties of the name field in the transaction_items table.
    // The name = "item_name" specifies that the column should be named item_name, which is consistent with the naming convention used in the TransactionItem entity.
    // The nullable = false indicates that the name field cannot be null, which ensures that each TransactionItem has a valid name.
    @Column(name = "item_name", nullable = false)
    private String name;

    // The @Column annotation is used to specify the properties of the unitPrice field in the transaction_items table.
    // The name = "unit_price" specifies that the column should be named unit_price, which is consistent with the naming convention used in the TransactionItem entity.
    // The nullable = false indicates that the unitPrice field cannot be null, which ensures that each TransactionItem has a valid unit price.
    // The precision = 10 and scale = 2 specify that the column should store decimal values with a maximum of 10 digits and 2 decimal places.
    @Column(name = "unit_price", nullable = false, precision = 10, scale = 2)
    private BigDecimal unitPrice;

    // The @Column annotation is used to specify the properties of the quantity field in the transaction_items table.
    // The nullable = false indicates that the quantity field cannot be null, which ensures that each TransactionItem has a valid quantity.
    // The quantity field is used to store the number of units of a specific SKU that have been scanned in a transaction. 
    // If a customer scans the same SKU multiple times, the quantity will increment accordingly, 
    // rather than creating duplicate rows for the same SKU. It helps maintain data integrity and provides an accurate count of items in a transaction.
    @Column(nullable = false)
    private int quantity;

    // The protected no-argument constructor is required by JPA (Java Persistence API) for entity classes.
    // JPA uses reflection to create instances of entity classes, and it requires a no-argument constructor to do so. 
    // By making the constructor protected, it prevents direct instantiation of the TransactionItem class from outside the class, while still allowing JPA to create instances of the class when loading data from the database. 
    // This is a common practice in JPA entity classes to ensure that the class can be properly managed by the persistence framework while maintaining encapsulation and control over how instances of the class are created.
    protected TransactionItem() {
        // Required by JPA.
    }

    // The public constructor is used to create a new instance of the TransactionItem class with the specified transaction, SKU, name, and unit price.
    // It initializes the transaction, sku, name, and unitPrice fields with the provided values, and sets the quantity field to 1, indicating that one unit of the specified SKU has been scanned in the transaction. 
    // This constructor is typically called when a new item is scanned during a checkout transaction, and it ensures that the TransactionItem is properly initialized with the relevant information.
    // The constructor takes the following parameters:
    // - CheckoutTransaction transaction: The checkout transaction to which this item belongs.
    // - String sku: The SKU (Stock Keeping Unit) of the item being scanned.
    // - String name: The name of the item being scanned.
    // - BigDecimal unitPrice: The unit price of the item being scanned.
    public TransactionItem(
            CheckoutTransaction transaction,
            String sku,
            String name,
            BigDecimal unitPrice
    ) {
        this.transaction = transaction;
        this.sku = sku;
        this.name = name;
        this.unitPrice = unitPrice;
        this.quantity = 1;
    }

    // The addOne() method is used to increment the quantity of the TransactionItem by 1.
    // This method is typically called when the same SKU is scanned again during a checkout transaction,
    // indicating that an additional unit of the item has been added to the transaction.
    public void addOne() {
        this.quantity++;
    }

    // The following getter methods are used to retrieve the values of the private fields in the TransactionItem class.
    // These methods provide read-only access to the fields, allowing other classes to access the values without directly modifying them.
    // The getId() method returns the unique identifier of the TransactionItem.
    // The getTransaction() method returns the CheckoutTransaction to which this item belongs.
    // The getSku() method returns the SKU of the item.
    // The getName() method returns the name of the item.
    // The getUnitPrice() method returns the unit price of the item.
    // The getQuantity() method returns the quantity of the item that has been scanned in the transaction.
    // These getter methods are important for encapsulation, as they allow controlled access to the private fields of the class while maintaining data integrity and preventing unauthorized modifications.
    public Long getId() {
        return id;
    }

    public CheckoutTransaction getTransaction() {
        return transaction;
    }

    public String getSku() {
        return sku;
    }

    public String getName() {
        return name;
    }

    public BigDecimal getUnitPrice() {
        return unitPrice;
    }

    public int getQuantity() {
        return quantity;
    }
}