spring.application.name=monolith-server

#Creates/uses a database file named self-checkout.db Places it in project’s data folder
# Tells Spring to use SQLite
# Lets JPA create/update database tables from your future Java entity classes
# Uses one database connection for now, which is safer while we first set up SQLite
spring.datasource.url=jdbc:sqlite:data/self-checkout.db
spring.datasource.driver-class-name=org.sqlite.JDBC

spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

spring.datasource.hikari.maximum-pool-size=1